# Header
menu:
  home: /
  archives: /archives
  opus: /opus
  reading: /reading
  riding: /riding
  about: /about
rss: /atom.xml

# Content
excerpt_link: 阅读全文 #文章太长"显示全文"
fancybox: true

# Sidebar
sidebar: bottom	#导航栏显示位置
widgets:
- category	#归档
# - tag
# - archive
- recent_posts	#最近文章
- tagcloud	#标签云
# - weibo
# - blogroll

# Miscellaneous
#google_analytics: verphen
baidu_tongji: true		# 百度统计
favicon: /imgs/favicon.png	#浏览器头部显示图标
twitter: verphen
google_plus: verphen
fb_admins: verphen
fb_app_id: verphen