# Header
menu:
  Home: /
  Archives: /archives
  Docs: /docs
  Opus: /opus
  Wiki: /wiki
  About: /about
rss: /atom.xml

# Content
excerpt_link: 阅读全文 #文章太长"显示全文"
fancybox: true

# Sidebar
sidebar: bottom	#导航栏显示位置
widgets:
- category	#归档
# - tag
# - archive
- recent_posts	#最近文章
- tagcloud	#标签云
# - weibo
# - blogroll

# Miscellaneous
google_analytics: verphen
favicon: /imgs/favicon.png	#浏览器头部显示图标
twitter: verphen
google_plus: verphen
fb_admins: verphen
fb_app_id: verphen