# Header
menu:
  home: /
  archives: /archives
  opus: /opus
  reading: /reading
  riding: /riding
  about: /about
rss: /atom.xml

# Content
excerpt_link: 阅读全文 #文章太长"显示全文"
fancybox: true

# Sidebar
sidebar: bottom	#导航栏显示位置

widgets:
	- category	#归档
	# - tag
	# - archive
	- recent_posts	#最近文章
	- tagcloud	#标签云
	# - weibo
	# - blogroll

# Miscellaneous
#google_analytics: effine
baidu_tongji: true		# 百度统计
busuanzi_tongji: true 		# 不蒜子统计访问量(http://service.ibruce.info/)
favicon: /imgs/favicon.png	# 浏览器头部显示图标
#twitter: effine
#google_plus: effine
#fb_admins: effine
#fb_app_id: effine

# gitalk comments
gitalk:
  enable: true 
  clientID: 4157d3de82a3693527ff
  clientSecret: 70aec74c8aa8ffed7d724d9c683bd1746aee54d5
  repo: blog-comments
  owner: effine
  admin: effine
  distractionFreeMode: true

#是否开启字数统计（不需要使用，直接设置值为false，或注释掉）
word_count: true
